debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: junni
    password: pw1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        .format_sql: true
        default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated

#---
## 지정한 DB로 테스트 진행 @ActiveProfiles("testdb")
#  spring:
#    config.activate.on-profile: testdb
#    datasource:
#      url: jdbc:h2:mem:board;mode=mysql
#      driver-class-name: org.h2.Driver
#    sql.init.mode: always
#    test.database.replace: none # @AutoContigureTestDatabase 대신 전역적으로 사용
